apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "manager.fullname" . }}
spec:
  dnsNames:
  - {{ include "manager.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
  - {{ include "manager.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  {{- range .Values.certificate.externalDNSNames }}
  - {{ . | quote }}
  {{- end }}
  {{- with .Values.certificate.externalIPAddresses }}
  ipAddresses:
  {{- range . }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  issuerRef:
    kind: Issuer
    name: {{ include "manager.fullname" . }}
  secretName: {{ include "manager.fullname" . }}-secret
