apiVersion: v1
kind: Service
metadata:
  name: {{ include "manager.fullname" . }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
    - name: https-api
      port: {{ .Values.tunnelPort | default 5443 }}
      targetPort: {{ .Values.tunnelPort | default 5443 }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: webhook
      port: 9443
      targetPort: 9443
      protocol: TCP
  selector:
    {{- include "manager.selectorLabels" . | nindent 4 }}
