apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kumquat:scheduler
rules:
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.kumquat.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.kumquat.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - apps.kumquat.io
  resources:
  - applications/status
  verbs:
  - list
  - watch
  - get
  - patch
  - update